global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'workshop-service'
    static_configs:
      - targets: ['workshop-service:80']
  - job_name: 'emergency-service'
    static_configs:
      - targets: ['emergency-service:80']
