global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'workshop-service'
    static_configs:
      - targets: ['workshop-service:80']
  - job_name: 'emergency-service'
    static_configs:
      - targets: ['emergency-service:80']
  - job_name: 'insurance-service'
    static_configs:
      - targets: ['insurance-service:80']
  - job_name: 'legal-service'
    static_configs:
      - targets: ['legal-service:80']
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:80']
